import Link from "next/link";

export const metadata = {
  title: "Giveaway Official Rules — The Heat Chart",
  description:
    "Official rules for The Heat Chart giveaways. No purchase necessary; purchases never affect odds.",
};

export default function RulesPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <p className="tag text-volt">Legal</p>
      <h1 className="display mt-2 text-4xl text-white">Giveaway Official Rules</h1>
      <p className="mt-1 text-sm text-smoke">
        These rules apply to every giveaway run on The Heat Chart unless the
        giveaway page says otherwise.
      </p>

      <div className="mt-8 space-y-6 text-sm leading-6 text-smoke">
        <section className="rounded-xl border border-volt/50 bg-volt/5 p-4">
          <p className="text-white">
            <strong>NO PURCHASE NECESSARY. A purchase does not improve your
            chances of winning — ever.</strong> Entries are earned exclusively
            by passing the Heat Check trivia game using free daily strikes.
            Paid strike packs apply only to leaderboard play and can never
            produce an entry.
          </p>
        </section>
        <section>
          <h2 className="display text-xl text-white">1. Sponsor</h2>
          <p className="mt-2">
            The Heat Chart, operator of theheatchart.com (&quot;Sponsor&quot;).
            Giveaways are not sponsored, endorsed, or administered by Nike,
            Jordan Brand, adidas, Facebook/Meta, or any other brand.
          </p>
        </section>
        <section>
          <h2 className="display text-xl text-white">2. Eligibility</h2>
          <p className="mt-2">
            Open to legal residents of the United States, 18 or older at time
            of entry. Void where prohibited or restricted by law. Employees and
            household members of the Sponsor are not eligible.
          </p>
        </section>
        <section>
          <h2 className="display text-xl text-white">3. How to enter</h2>
          <p className="mt-2">
            Create a free account and pass the Heat Check ({" "}
            <Link href="/quiz" className="text-volt underline">theheatchart.com/quiz</Link>{" "}
            ) during the entry period using free daily strikes — each qualifying
            pass earns one (1) entry. Free strikes refill every day, so free
            entry is available daily. Entry limits, the prize, and the entry
            period for each giveaway are stated on the{" "}
            <Link href="/giveaway" className="text-volt underline">giveaway page</Link>.
          </p>
        </section>
        <section>
          <h2 className="display text-xl text-white">4. Winner selection &amp; notification</h2>
          <p className="mt-2">
            One winner is drawn at random from all valid entries after the
            entry period closes. Odds depend on the number of valid entries.
            The winner is notified at their account email and must respond
            within 7 days or an alternate winner may be drawn. Winning may
            require completing a brief eligibility affidavit.
          </p>
        </section>
        <section>
          <h2 className="display text-xl text-white">5. Prize</h2>
          <p className="mt-2">
            The prize (including approximate retail value) is described on the
            giveaway page. No cash substitution except at Sponsor&apos;s sole
            discretion. Shipping is free within the continental US. Taxes, if
            any, are the winner&apos;s responsibility.
          </p>
        </section>
        <section>
          <h2 className="display text-xl text-white">6. General conditions</h2>
          <p className="mt-2">
            Entries generated by scripts, duplicate accounts, or quiz
            exploitation are void and may result in disqualification. Sponsor
            may cancel or modify a giveaway if fraud or technical failure
            compromises it. By entering you accept these rules; winner&apos;s first
            name may be displayed on the site&apos;s past-winners list.
          </p>
        </section>
        <section>
          <h2 className="display text-xl text-white">7. Social platforms (Meta release)</h2>
          <p className="mt-2">
            This promotion is in no way sponsored, endorsed, administered
            by, or associated with Meta Platforms, Inc. (Facebook or
            Instagram) or any other social platform. By entering, you
            understand that you are providing your information to the
            Sponsor and not to Meta, and you release Meta from any and all
            liability related to this promotion. Entry happens only on
            theheatchart.com — liking, sharing, or commenting on a social
            post is never a method of entry and never affects odds.
          </p>
        </section>
        <p className="border-t border-edge pt-4 text-xs">
          Draft rules pending attorney review — sweepstakes law varies by
          state. A named winner list is available on request to{" "}
          <span className="text-white">hello@theheatchart.com</span>.
        </p>
      </div>
    </div>
  );
}
